# -*- coding: utf-8 -*-
"""Mask

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MQBuNPpsJ-t_He1u3-kXNb81101MAoQU
"""

from PIL import Image


def mask(im_height, im_width):
    mask = Image.new('L', (im_width, im_height), 0)
    draw = PIL.ImageDraw.Draw(mask)

    # Create each serpent of vertexes in the mask.
    for serpent_id in range(random.randint(1, 7)):
        vertex_num = random.randint(2, 7)
        x_start = random.randint(0, im_width)
        y_start = random.randint(0, im_height)
        vertex_position = [(x_start, y_start)]

        # Create each vertex line with a series of overlapping round ellipses.
        for i in range(vertex_num):
            start_point = (vertex_position[-1][0], vertex_position[-1][1])
            angle = random.uniform(0.0, 2.0) * math.pi
            vertex_length = random.randint(10, 50)
            end_point = ((start_point[0] + vertex_length * math.cos(angle)),
                         (start_point[1] + vertex_length * math.sin(angle)))
            vertex_position.append(end_point)
            ellipse_num = random.randint(75, 150)

            # Create ellipses with radius large enough so that they overlap.
            ellipse_radius = 6 * vertex_length / ellipse_num

            # Create the series of ellipse on the vertex line.
            for ell in range(ellipse_num):
                new_x = start_point[0] + ell * (end_point[0] - start_point[0]) / ellipse_num
                new_y = start_point[1] + ell * (end_point[1] - start_point[1]) / ellipse_num
                draw.ellipse([new_x - ellipse_radius, new_y - ellipse_radius,
                              new_x + ellipse_radius, new_y + ellipse_radius],
                             fill=255, outline=255, width=1)

    return mask